GET http://localhost:8081/
###
POST http://localhost:8081/create
content-type: application/json

{
    "username":"ali",
    "password":"ashdfwrwe.e"
}

###
GET http://localhost:8081/users

###
POST http://localhost:8081/exists
Content-Type: application/json

{
    "rfid":"1632039871174-ae07b3fa"
}



########   for kubernetes nodePort #########


GET http://94.237.53.66:30007/

###
POST http://94.237.53.66:30007/create
content-type: application/json

{
    "username":"Ali@gmail.com",
    "password":"sj234.sE#"
}

###
GET http://94.237.53.66:30007/users

###
POST http://94.237.53.66:30007/exists
Content-Type: application/json

{
    "rfid":"1631935739464-4a180a19"
}

########   for kubernetes ingress #########


GET http://94.237.53.66/admin/
HOST: hello-world.info

###
POST http://94.237.53.66/admin/create
HOST: hello-world.info
content-type: application/json

{
    "username":"Ali@gmail.com",
    "password":"sj234.sE#"
}

###
GET http://94.237.53.66/admin/users
HOST: hello-world.info

###
POST http://94.237.53.66/admin/exists
HOST: hello-world.info
Content-Type: application/json

{
    "rfid":"1631935739464-4a180a19"
}