GET http://localhost:8081/
###
POST http://localhost:8081/create
content-type: application/json

{
    "username":"mohammad234",
    "password":"ashdfwrwe.e"
}

###
GET http://localhost:8081/users

###
POST http://localhost:8081/exists
Content-Type: application/json

{
    "rfid":"1631691633675-45f01a4f"
}