GET http://localhost:8081/
###
POST http://localhost:8081/create
content-type: application/json

{
    "username":"mohammad234",
    "password":"ashdfwrwe.e"
}

###
GET http://localhost:8081/users

###
POST http://localhost:8081/exists
Content-Type: application/json

{
    "rfid":"1631691633675-45f01a4f"
}



########   for kubernetes nodePort #########


GET http://94.237.53.66:30007/
###
POST http://94.237.53.66:30007/create
content-type: application/json

{
    "username":"Ali@gmail.com",
    "password":"sj234.sE#"
}

###
GET http://94.237.53.66:30007/users

###
POST http://94.237.53.66:30007/exists
Content-Type: application/json

{
    "rfid":"1631785469788-4a2a8f7d"
}