##############################################
#         (start Admin db deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: admin-db
  template:
    metadata:
      labels:
        app: admin-db
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: admin-mount
              mountPath: /data
      volumes:
        - name: admin-mount
          hostPath:
            path: /admin-mount/data

---
#         (end Admin db deployment)
##############################################

##############################################
#     (start Admin db service)

apiVersion: v1
kind: Service
metadata:
  name: admin-db
spec:
  selector:
    app: admin-db
  ports:
    - port: 6379
      protocol: TCP

#     (end Admin db service)
##############################################