##############################################
#         (start admin deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-depl
  template:
    metadata:
      labels:
        app: admin-depl
    spec:
      containers:
        - name: admin-depl
          image: vectormj/adminapp
          env:
            - name: ADMINPORT
              value: "8081"
          ports:
            - containerPort: 8081
---
#         (end admin deployment)
##############################################

##############################################
#         (start admin service)
apiVersion: v1
kind: Service
metadata:
  name: admin-depl
spec:
  selector:
    app: admin-depl
  ports:
    - port: 8081
      protocol: TCP
#         (end admin service)
##############################################
