apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
    spec:
      containers:
        - name: adminapp-depl
          image: vectormj/adminapp
          env:
            - name: ADMINPORT
              value: "8081"
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: admin-srv
spec:
  selector:
    app: admin
  ports:
    - port: 8081
      protocol: TCP
