##############################################
#         (start log db deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-db
  template:
    metadata:
      labels:
        app: log-db
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: log-mount
              mountPath: /data
      volumes:
        - name: log-mount
          hostPath:
            path: /log-mount/data
---
#         (end log db deployment)
##############################################

##############################################
#           (start log db service)

apiVersion: v1
kind: Service
metadata:
  name: log-db
spec:
  selector:
    app: log-db
  ports:
    - port: 6379
      protocol: TCP

#             (end log db service)
##############################################