##############################################
#         (start log deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-depl
  template:
    metadata:
      labels:
        app: log-depl
    spec:
      containers:
        - name: log-depl
          image: vectormj/logapp
          env:
            - name: ADMINPORT
              value: "8082"
          ports:
            - containerPort: 8082
---
#         (end log deployment)
##############################################

##############################################
#         (start log service)
apiVersion: v1
kind: Service
metadata:
  name: log-depl
spec:
  selector:
    app: log-depl
  ports:
    - port: 8082
      protocol: TCP
#         (end log service)
##############################################
