apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log
  template:
    metadata:
      labels:
        app: log
    spec:
      containers:
        - name: logapp-depl
          image: vectormj/logapp
          env:
            - name: ADMINPORT
              value: "8082"
          ports:
            - containerPort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: log-srv
spec:
  selector:
    app: log-depl
  ports:
    - port: 8082
      protocol: TCP
