apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-db
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: log-db
  template:
    metadata:
      labels:
        app: log-db
    spec:
      containers:
        - name: redis
          image: redis:latest
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: log-mount
              mountPath: /data
      volumes:
        - name: log-mount
          hostPath:
            path: /log-mount/data

---
apiVersion: v1
kind: Service
metadata:
  name: log-db
spec:
  selector:
    app: log-db
  ports:
    - port: 6379
      protocol: TCP
# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: admin-redis-pv
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   capacity:
#     storage: 300Mi
#   hostPath:
#     path: "/mnt/data"
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: admin-redis-pv
# spec:
#   storageClassName: manual
#   accessModes:
#     - ReadWriteOnce
#   resources:
#     requests:
#       storage: 300Mi
