apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-net
spec:
  rules:
    - http:
        paths:
          - path: /admin
            backend:
              serviceName: admin-srv
              servicePort: 8081
          - path: /log
            backend:
              serviceName: log-srv
              servicePort: 8082
---
apiVersion: v1
kind: Service
metadata:
  name: admin-nodeport
spec:
  type: NodePort
  selector:
    app: admin
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 30007
---
apiVersion: v1
kind: Service
metadata:
  name: log-nodeport
spec:
  type: NodePort
  selector:
    app: log
  ports:
    - port: 8082
      targetPort: 8082
      nodePort: 30008
