##############################################
#              (NodePort Services)
# apiVersion: v1
# kind: Service
# metadata:
#   name: admin-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: admin-depl
#   ports:
#     - port: 8081
#       targetPort: 8081
#       nodePort: 30007
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: log-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: log
#   ports:
#     - port: 8082
#       targetPort: 8082
#       nodePort: 30008
##############################################

##############################################
#      (Start Ingress for admin service)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-admin
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: $2
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - pathType: Prefix
            path: /(admin)(.*)
            backend:
              service:
                name: admin-depl
                port:
                  number: 8081

#      (End Ingress for admin service)
##############################################

##############################################
#      (Start Ingress for log service)
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-log
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /log$2
    nginx.ingress.kubernetes.io/use-regex: "true"

spec:
  rules:
    - host: hello-world.info
      http:
        paths:
          - pathType: Prefix
            path: /(log)(.*)
            backend:
              service:
                name: log-depl
                port:
                  number: 8082
#      (End Ingress for log service)
##############################################
