# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: admin-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: admin
#   ports:
#     - port: 8081
#       targetPort: 8081
#       nodePort: 30007
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: log-nodeport
# spec:
#   type: NodePort
#   selector:
#     app: log
#   ports:
#     - port: 8082
#       targetPort: 8082
#       nodePort: 30008

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-net
  annotations:
    ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: foo.bar.com
      http:
        paths:
          - path: /admin
            pathType: Prefix
            backend:
              service:
                name: admin-srv
                port:
                  number: 8081
          - path: /log
            pathType: Prefix
            backend:
              service:
                name: log-srv
                port:
                  number: 8082
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: test-ingress
spec:
  defaultBackend:
    service:
      name: admin-srv
      port:
        number: 8081
