
GET http://localhost:8082/

###
POST http://localhost:8082/gate
Content-Type: application/json

{
    "gtype":"0",
    "rfid":"1631940375367-a214ead8"
}   

###
GET http://localhost:8082/allLogs

###
GET http://localhost:8082/loginlogs


########   for kubernetes nodePort #########


GET http://94.237.53.66:30008/

###
POST http://94.237.53.66:30008/gate
Content-Type: application/json

{
    "gtype":"0",
    "rfid":"1631785469788-4a2a8f7d"
}

###
GET http://94.237.53.66:30008/allLogs
