
GET http://localhost:8082/

###
POST http://localhost:8082/gate
Content-Type: application/json

{
    "gtype":"1",
    "rfid":"1631691643812-91f11d04"
}

###
GET http://localhost:8082/allLogs


########   for kubernetes nodePort #########


GET http://94.237.53.66:30008/

###
POST http://94.237.53.66:30008/gate
Content-Type: application/json

{
    "gtype":"1",
    "rfid":"1631776848266-2518d7ec"
}

###
GET http://94.237.53.66:30008/allLogs
