
GET http://localhost:8082/

###
POST http://localhost:8082/gate
Content-Type: application/json

{
    "gtype":"0",
    "rfid":"1631940375367-a214ead8"
}   

###
GET http://localhost:8082/allLogs

###
GET http://localhost:8082/loginlogs


########   for kubernetes nodePort #########


GET http://94.237.53.66:30008/
HOST: hello-world.info

###
POST http://94.237.53.66:30008/gate
Content-Type: application/json

{
    "gtype":"1",
    "rfid":"1631935726064-a41f83e2"
}

###
GET http://94.237.53.66:30008/allLogs

###
GET http://94.237.53.66:30008/loginlogs
